import type {
  BotPersonality,
  GameConfig,
  GameContent,
  ItemDefinition,
  PvEEnemyDefinition,
  StageDefinition,
  TraitDefinition,
  UnitDefinition,
  UnitFormDefinition,
} from "./types";
import { canonicalItemRecipeKey } from "./items";

const ability = (
  id: string,
  name: string,
  description: string,
  power: number,
  targeting: UnitDefinition["ability"]["targeting"],
  pattern: UnitDefinition["ability"]["pattern"],
  extras: Partial<UnitDefinition["ability"]> = {},
): UnitDefinition["ability"] => ({
  id,
  name,
  description,
  targeting,
  pattern,
  effect: "damage",
  power,
  castAnimationMs: 500,
  ...extras,
});

export const UNIT_DEFINITIONS: UnitDefinition[] = [
  {
    id: "nami",
    name: "Nami",
    cost: 1,
    traits: ["straw-hat", "specialist"],
    stats: {
      health: 520,
      attack: 42,
      defense: 12,
      range: 4,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: ability(
      "thunderbolt-tempo",
      "Thunderbolt Tempo",
      "Calls lightning onto an enemy and nearby foes, dealing damage and draining 15 Energy from survivors.",
      145,
      "nearest-enemy",
      "adjacent",
      { energyDrain: 15 },
    ),
    assetPath: "/assets/characters/nami.png",
  },
  {
    id: "usopp",
    name: "Usopp",
    cost: 1,
    traits: ["straw-hat", "marksman"],
    stats: {
      health: 500,
      attack: 52,
      defense: 10,
      range: 5,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "exploding-star",
      "Exploding Star",
      "Fires an explosive shot at the farthest enemy, damaging nearby enemies and blasting surviving targets backward.",
      160,
      "farthest-enemy",
      "adjacent",
      { signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/usopp.png",
  },
  {
    id: "chopper",
    name: "Chopper",
    cost: 1,
    traits: ["straw-hat", "guardian"],
    stats: {
      health: 650,
      attack: 38,
      defense: 18,
      range: 2,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: {
      ...ability(
        "emergency-cure",
        "Emergency Cure",
        "Heals the most injured ally. Allies at 35% HP or lower also receive an emergency shield.",
        220,
        "lowest-health-ally",
        "single-ally",
      ),
      effect: "heal",
      requiresTarget: false,
      conditionalShield: { healthThresholdPercent: 35, power: 100 },
    },
    assetPath: "/assets/characters/chopper.png",
  },
  {
    id: "tashigi",
    name: "Tashigi",
    cost: 1,
    traits: ["navy", "swordsman"],
    stats: {
      health: 600,
      attack: 58,
      defense: 18,
      range: 1,
      attackIntervalMs: 1_100,
      moveIntervalMs: 400,
    },
    ability: ability(
      "flash-cut",
      "Flash Cut",
      "Lunges beside the nearest enemy and lands a precise strike.",
      190,
      "nearest-enemy",
      "single",
      {
        requiresTarget: false,
        signatureMechanics: [{ kind: "lunge" }],
      },
    ),
    assetPath: "/assets/characters/tashigi.png",
  },
  {
    id: "koby",
    name: "Koby",
    cost: 1,
    traits: ["navy", "brawler"],
    stats: {
      health: 610,
      attack: 54,
      defense: 16,
      range: 1,
      attackIntervalMs: 1_050,
      moveIntervalMs: 400,
    },
    ability: ability(
      "shave-strike",
      "Shave Strike",
      "Rapidly closes on the nearest enemy and lands a disciplined strike.",
      165,
      "nearest-enemy",
      "single",
      {
        requiresTarget: false,
        signatureMechanics: [{ kind: "lunge" }],
      },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "koala",
    name: "Koala",
    cost: 1,
    traits: ["revolutionary", "brawler"],
    stats: {
      health: 560,
      attack: 50,
      defense: 14,
      range: 1,
      attackIntervalMs: 1_050,
      moveIntervalMs: 400,
    },
    ability: ability(
      "fish-man-karate",
      "Fish-Man Karate",
      "Strikes the target area with Fish-Man Karate, damaging and briefly disrupting nearby enemies.",
      135,
      "nearest-enemy",
      "adjacent",
      { stunMs: 300 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "sanji",
    name: "Sanji",
    cost: 2,
    traits: ["straw-hat", "brawler"],
    stats: {
      health: 720,
      attack: 68,
      defense: 22,
      range: 1,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "diable-jambe",
      "Diable Jambe",
      "A burning kick that damages, scorches and knocks a surviving target backward.",
      235,
      "nearest-enemy",
      "single",
      {
        burnPower: 18,
        burnDurationMs: 3_000,
        signatureMechanics: [{ kind: "knockback" }],
      },
    ),
    assetPath: "/assets/characters/sanji.png",
  },
  {
    id: "robin",
    name: "Robin",
    cost: 2,
    traits: ["straw-hat", "revolutionary", "specialist"],
    stats: {
      health: 620,
      attack: 48,
      defense: 16,
      range: 4,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "clutch",
      "Clutch",
      "Damages and immobilizes the enemy while draining 15 Energy from survivors.",
      205,
      "lowest-health-enemy",
      "single",
      { stunMs: 1_200, energyDrain: 15 },
    ),
    assetPath: "/assets/characters/robin.png",
  },
  {
    id: "smoker",
    name: "Smoker",
    cost: 2,
    traits: ["navy", "guardian"],
    stats: {
      health: 820,
      attack: 62,
      defense: 28,
      range: 2,
      attackIntervalMs: 1_400,
      moveIntervalMs: 500,
    },
    ability: ability(
      "white-blow",
      "White Blow",
      "Sweeps a line of enemies and pushes surviving targets backward.",
      180,
      "nearest-enemy",
      "line",
      { signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/smoker.png",
  },
  {
    id: "sabo",
    name: "Sabo",
    cost: 2,
    traits: ["revolutionary", "brotherhood", "brawler"],
    stats: {
      health: 760,
      attack: 72,
      defense: 23,
      range: 1,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "dragon-claw",
      "Dragon Claw",
      "Crushes the target area with Dragon Claw, damaging and briefly stunning nearby enemies.",
      190,
      "nearest-enemy",
      "adjacent",
      { stunMs: 600 },
    ),
    assetPath: "/assets/characters/sabo.png",
  },
  {
    id: "franky",
    name: "Franky",
    cost: 2,
    traits: ["straw-hat", "guardian"],
    stats: {
      health: 860,
      attack: 66,
      defense: 30,
      range: 2,
      attackIntervalMs: 1_150,
      moveIntervalMs: 500,
    },
    ability: ability(
      "coup-de-vent",
      "Coup de Vent",
      "Releases a compressed-air blast into an enemy cluster, damaging nearby enemies and blasting survivors backward.",
      205,
      "nearest-enemy",
      "adjacent",
      { signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "brook",
    name: "Brook",
    cost: 2,
    traits: ["straw-hat", "swordsman"],
    stats: {
      health: 660,
      attack: 72,
      defense: 18,
      range: 2,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "soul-solid",
      "Soul Solid",
      "Sends a freezing sword technique through an enemy line, damaging and briefly stunning affected enemies.",
      215,
      "farthest-enemy",
      "line",
      { stunMs: 400 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "ivankov",
    name: "Ivankov",
    cost: 2,
    traits: ["revolutionary", "specialist"],
    stats: {
      health: 700,
      attack: 52,
      defense: 20,
      range: 3,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: {
      ...ability(
        "healing-hormone",
        "Healing Hormone",
        "Restores the most injured ally and shields them when they were already at half health or lower.",
        260,
        "lowest-health-ally",
        "single-ally",
      ),
      effect: "heal",
      requiresTarget: false,
      conditionalShield: { healthThresholdPercent: 50, power: 120 },
    },
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "luffy",
    name: "Luffy",
    cost: 3,
    traits: [
      "straw-hat",
      "supernova",
      "brotherhood",
      "captain",
      "brawler",
    ],
    stats: {
      health: 900,
      attack: 80,
      defense: 28,
      range: 2,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "gum-gum-gatling",
      "Gum-Gum Gatling",
      "Unleashes a rapid three-hit Gatling barrage across nearby enemies, blasting surviving targets backward.",
      75,
      "nearest-enemy",
      "adjacent",
      { hits: 3, signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/luffy.png",
  },
  {
    id: "zoro",
    name: "Zoro",
    cost: 3,
    traits: ["straw-hat", "supernova", "swordsman"],
    stats: {
      health: 880,
      attack: 92,
      defense: 30,
      range: 1,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "oni-giri",
      "Oni Giri",
      "Strikes three times. Remaining strikes redirect after a KO, and the final strike deals more damage to low-health enemies.",
      355,
      "lowest-health-enemy",
      "single",
      {
        sequentialStrike: {
          hitWeightsBasisPoints: [3_000, 3_000, 4_000],
          retargetOnKill: "nearest-in-range",
          finalHitBonus: {
            healthThresholdPercent: 35,
            damageBonusPercent: 25,
          },
        },
      },
    ),
    assetPath: "/assets/characters/zoro.png",
  },
  {
    id: "kid",
    name: "Kid",
    cost: 3,
    traits: ["supernova", "captain"],
    stats: {
      health: 920,
      attack: 78,
      defense: 32,
      range: 2,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "magnetic-crush",
      "Magnetic Crush",
      "Crushes nearby enemies with magnetism, stunning them and pulling surviving targets one step closer.",
      275,
      "nearest-enemy",
      "adjacent",
      { stunMs: 800, signatureMechanics: [{ kind: "pull" }] },
    ),
    assetPath: "/assets/characters/kid.png",
  },
  {
    id: "crocodile",
    name: "Crocodile",
    cost: 3,
    traits: ["warlord", "specialist", "marksman"],
    stats: {
      health: 760,
      attack: 74,
      defense: 22,
      range: 4,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "desert-spada",
      "Desert Spada",
      "Sends a cutting blade of dehydrating sand through an enemy line, damaging and draining 15 Energy from survivors.",
      300,
      "farthest-enemy",
      "line",
      { energyDrain: 15 },
    ),
    assetPath: "/assets/characters/crocodile.png",
  },
  {
    id: "jinbe",
    name: "Jinbe",
    cost: 3,
    traits: ["straw-hat", "guardian"],
    stats: {
      health: 1_020,
      attack: 76,
      defense: 38,
      range: 1,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "fish-man-shockwave",
      "Fish-Man Shockwave",
      "Strikes the nearby enemy formation with Fish-Man Karate, damaging the cluster and blasting survivors backward.",
      255,
      "nearest-enemy",
      "adjacent",
      { signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "kuma",
    name: "Kuma",
    cost: 3,
    traits: ["revolutionary", "guardian"],
    stats: {
      health: 960,
      attack: 70,
      defense: 36,
      range: 2,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "ursus-shock",
      "Ursus Shock",
      "Releases a battlefield-wide pressure shock, lightly damaging every enemy and blasting survivors backward.",
      145,
      "nearest-enemy",
      "all-enemies",
      {
        castAnimationMs: 600,
        signatureMechanics: [{ kind: "knockback" }],
      },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "law",
    name: "Law",
    cost: 4,
    traits: ["supernova", "warlord", "captain"],
    stats: {
      health: 900,
      attack: 86,
      defense: 28,
      range: 3,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "room-shambles",
      "ROOM/Shambles",
      "Manipulates a wide ROOM, damaging every enemy and pulling surviving foes one step toward Law.",
      195,
      "nearest-enemy",
      "all-enemies",
      { signatureMechanics: [{ kind: "pull" }] },
    ),
    assetPath: "/assets/characters/law.png",
  },
  {
    id: "ace",
    name: "Ace",
    cost: 4,
    traits: ["brotherhood", "marksman"],
    stats: {
      health: 820,
      attack: 90,
      defense: 22,
      range: 5,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "fire-fist",
      "Fire Fist",
      "Engulfs a cluster in a blazing fist, burning enemies and blasting survivors backward.",
      390,
      "farthest-enemy",
      "adjacent",
      {
        burnPower: 28,
        burnDurationMs: 4_000,
        signatureMechanics: [{ kind: "knockback" }],
      },
    ),
    assetPath: "/assets/characters/ace.png",
  },
  {
    id: "hancock",
    name: "Hancock",
    cost: 4,
    traits: ["warlord", "specialist"],
    stats: {
      health: 850,
      attack: 82,
      defense: 26,
      range: 4,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "mero-mero",
      "Mero Mero",
      "Petrifies enemies across the battlefield, damaging and stunning them while draining 10 Energy from survivors.",
      235,
      "nearest-enemy",
      "all-enemies",
      { stunMs: 1_000, energyDrain: 10 },
    ),
    assetPath: "/assets/characters/hancock.png",
  },
  {
    id: "doflamingo",
    name: "Doflamingo",
    cost: 4,
    traits: ["warlord", "specialist"],
    stats: {
      health: 900,
      attack: 88,
      defense: 28,
      range: 4,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "string-bind",
      "String Bind",
      "Binds a vulnerable enemy cluster in razor strings, damaging and stunning them before pulling survivors closer.",
      315,
      "lowest-health-enemy",
      "adjacent",
      { stunMs: 1_400, signatureMechanics: [{ kind: "pull" }] },
    ),
    assetPath: "/assets/characters/doflamingo.png",
  },
  {
    id: "kizaru",
    name: "Kizaru",
    cost: 4,
    traits: ["navy", "marksman"],
    stats: {
      health: 800,
      attack: 100,
      defense: 20,
      range: 5,
      attackIntervalMs: 950,
      moveIntervalMs: 500,
    },
    ability: ability(
      "sacred-jewel",
      "Sacred Jewel",
      "Fires a concentrated beam of light through the farthest enemy line, dealing heavy damage while ignoring 40% of Defense.",
      420,
      "farthest-enemy",
      "line",
      { castAnimationMs: 600, defensePiercePercent: 40 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "kuzan",
    name: "Kuzan",
    cost: 4,
    traits: ["navy", "specialist"],
    stats: {
      health: 900,
      attack: 84,
      defense: 30,
      range: 4,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "ice-age",
      "Ice Age",
      "Freezes the battlefield, damaging every enemy and briefly stunning survivors.",
      190,
      "nearest-enemy",
      "all-enemies",
      { stunMs: 700, castAnimationMs: 650 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "akainu",
    name: "Akainu",
    cost: 4,
    traits: ["navy", "brawler"],
    stats: {
      health: 980,
      attack: 94,
      defense: 34,
      range: 2,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "great-eruption",
      "Great Eruption",
      "Erupts magma through the nearby enemy formation, dealing heavy damage and leaving survivors burning.",
      340,
      "nearest-enemy",
      "adjacent",
      { burnPower: 32, burnDurationMs: 4_000, castAnimationMs: 650 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "garp",
    name: "Garp",
    cost: 5,
    traits: ["navy", "guardian", "brawler"],
    stats: {
      health: 1_250,
      attack: 110,
      defense: 45,
      range: 2,
      attackIntervalMs: 1_100,
      moveIntervalMs: 400,
    },
    ability: ability(
      "galaxy-impact",
      "Galaxy Impact",
      "Shatters the battlefield with a colossal shock wave, damaging every enemy and blasting survivors backward.",
      360,
      "nearest-enemy",
      "all-enemies",
      {
        castAnimationMs: 700,
        signatureMechanics: [{ kind: "knockback" }],
      },
    ),
    assetPath: "/assets/characters/garp.png",
  },
  {
    id: "mihawk",
    name: "Mihawk",
    cost: 5,
    traits: ["warlord", "swordsman"],
    stats: {
      health: 1_000,
      attack: 135,
      defense: 36,
      range: 3,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "black-blade-wave",
      "Black Blade Wave",
      "Launches an overwhelming slash through an enemy line, ignoring 50% of their Defense.",
      660,
      "farthest-enemy",
      "line",
      { castAnimationMs: 700, defensePiercePercent: 50 },
    ),
    assetPath: "/assets/characters/mihawk.png",
  },
  {
    id: "shanks",
    name: "Shanks",
    cost: 5,
    traits: ["emperor", "captain", "swordsman"],
    stats: {
      health: 1_080,
      attack: 128,
      defense: 40,
      range: 2,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "divine-departure",
      "Divine Departure",
      "Unleashes an overwhelming Haki-infused strike through the nearby enemy cluster, partially ignoring Defense.",
      540,
      "nearest-enemy",
      "adjacent",
      { defensePiercePercent: 35, castAnimationMs: 700 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "blackbeard",
    name: "Blackbeard",
    cost: 5,
    traits: ["emperor", "captain", "specialist"],
    stats: {
      health: 1_220,
      attack: 105,
      defense: 40,
      range: 3,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "black-hole",
      "Black Hole",
      "Creates a battlefield-wide gravitational void, damaging every enemy, draining Energy, then pulling survivors closer.",
      220,
      "nearest-enemy",
      "all-enemies",
      {
        energyDrain: 20,
        castAnimationMs: 700,
        signatureMechanics: [{ kind: "pull" }],
      },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
];

export const FORM_DEFINITIONS: UnitFormDefinition[] = [
  {
    id: "robin-demonio-fleur",
    baseDefinitionId: "robin",
    name: "Robin — Demonio Fleur",
    lifecycle: "persistent",
    ability: ability(
      "demonio-fleur",
      "Demonio Fleur",
      "Crushes the lowest-health enemy's area, stunning enemies and draining 20 Energy from survivors.",
      180,
      "lowest-health-enemy",
      "adjacent",
      { stunMs: 1_400, energyDrain: 20 },
    ),
  },
  {
    id: "luffy-gear-4-boundman",
    baseDefinitionId: "luffy",
    name: "Luffy — Gear 4: Boundman",
    lifecycle: "persistent",
    stats: {
      health: 990,
      attack: 86,
      defense: 34,
      range: 1,
      attackIntervalMs: 1_000,
    },
    ability: ability(
      "kong-gun",
      "Kong Gun",
      "Drives a hardened fist into the nearest enemy, stunning and blasting a surviving target backward.",
      285,
      "nearest-enemy",
      "single",
      { stunMs: 600, signatureMechanics: [{ kind: "knockback" }] },
    ),
  },
  {
    id: "luffy-gear-4-snakeman",
    baseDefinitionId: "luffy",
    name: "Luffy — Gear 4: Snakeman",
    lifecycle: "persistent",
    stats: {
      health: 850,
      attack: 78,
      defense: 24,
      range: 4,
      attackIntervalMs: 700,
    },
    ability: ability(
      "jet-culverin",
      "Jet Culverin",
      "Launches four accelerating strikes at a weakened enemy, redirecting remaining blows after a knockout.",
      300,
      "lowest-health-enemy",
      "single",
      {
        sequentialStrike: {
          hitWeightsBasisPoints: [2_500, 2_500, 2_500, 2_500],
          retargetOnKill: "nearest-in-range",
        },
      },
    ),
  },
  {
    id: "chopper-monster-point",
    baseDefinitionId: "chopper",
    name: "Chopper — Monster Point",
    lifecycle: "battle-temporary",
    stats: {
      health: 800,
      attack: 60,
      defense: 28,
      range: 1,
    },
    ability: ability(
      "monster-point-slam",
      "Monster Point Slam",
      "Smashes the nearest enemy cluster with overwhelming force, damaging and stunning nearby foes.",
      250,
      "nearest-enemy",
      "adjacent",
      { stunMs: 600 },
    ),
  },
];

export const TRAIT_DEFINITIONS: TraitDefinition[] = [
  {
    id: "straw-hat",
    name: "Straw Hat",
    category: "origin",
    description: "Crew bonds grant health and faster attacks.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "max-health-percent", value: 10 }],
        label: "+10% health",
      },
      {
        required: 4,
        effects: [
          { kind: "max-health-percent", value: 15 },
          { kind: "attack-speed-percent", value: 10 },
        ],
        label: "+15% health, +10% attack speed",
      },
      {
        required: 6,
        effects: [
          { kind: "max-health-percent", value: 25 },
          { kind: "attack-speed-percent", value: 20 },
        ],
        label: "+25% health, +20% attack speed",
      },
    ],
  },
  {
    id: "navy",
    name: "Navy",
    category: "origin",
    description: "Disciplined formations gain defenses.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "defense-flat", value: 14 }],
        label: "+14 defense",
      },
      {
        required: 3,
        effects: [
          { kind: "defense-flat", value: 28 },
          { kind: "shield-flat", value: 100 },
        ],
        label: "+28 defense and 100 shield",
      },
    ],
  },
  {
    id: "warlord",
    name: "Warlord",
    category: "origin",
    description: "Veterans begin energized and drain life.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "omnivamp-percent", value: 8 },
          { kind: "starting-energy", value: 10 },
        ],
        label: "8% omnivamp, +10 energy",
      },
      {
        required: 4,
        effects: [
          { kind: "omnivamp-percent", value: 18 },
          { kind: "starting-energy", value: 25 },
        ],
        label: "18% omnivamp, +25 energy",
      },
    ],
  },
  {
    id: "supernova",
    name: "Supernova",
    category: "origin",
    description: "Ambition increases attack and snowballs after takedowns.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "attack-percent", value: 8 },
          { kind: "stacking-attack-percent", value: 3 },
        ],
        label: "+8% attack, +3% per takedown",
      },
      {
        required: 4,
        effects: [
          { kind: "attack-percent", value: 18 },
          { kind: "stacking-attack-percent", value: 7 },
        ],
        label: "+18% attack, +7% per takedown",
      },
    ],
  },
  {
    id: "brotherhood",
    name: "Brotherhood",
    category: "origin",
    description: "At low health, sworn brothers gain an emergency shield.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "emergency-shield-percent", value: 22 }],
        label: "22% emergency shield",
      },
      {
        required: 3,
        effects: [{ kind: "emergency-shield-percent", value: 38 }],
        label: "38% emergency shield",
      },
    ],
  },
  {
    id: "revolutionary",
    name: "Revolutionary",
    category: "origin",
    description: "Unpredictable footwork grants dodge.",
    tiers: [
      {
        required: 1,
        effects: [{ kind: "dodge-percent", value: 10 }],
        label: "+10% dodge",
      },
      {
        required: 2,
        effects: [{ kind: "dodge-percent", value: 20 }],
        label: "+20% dodge",
      },
    ],
  },
  {
    id: "emperor",
    name: "Emperor",
    category: "origin",
    description:
      "Emperors embolden the entire crew, with a stronger bonus when multiple Emperors unite.",
    tiers: [
      {
        required: 1,
        effects: [
          { kind: "max-health-percent", value: 4 },
          { kind: "attack-percent", value: 4 },
        ],
        label: "+4% health and attack",
      },
      {
        required: 2,
        effects: [
          { kind: "max-health-percent", value: 8 },
          { kind: "attack-percent", value: 8 },
        ],
        label: "+8% health and attack",
      },
    ],
  },
  {
    id: "captain",
    name: "Captain",
    category: "role",
    description: "Captains inspire their formation with opening shields.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "shield-flat", value: 100 }],
        label: "100 starting shield",
      },
      {
        required: 3,
        effects: [{ kind: "shield-flat", value: 225 }],
        label: "225 starting shield",
      },
    ],
  },
  {
    id: "brawler",
    name: "Brawler",
    category: "role",
    description: "Close-range fighters gain health and speed.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "max-health-percent", value: 6 },
          { kind: "attack-speed-percent", value: 4 },
        ],
        label: "+6% health, +4% attack speed",
      },
      {
        required: 4,
        effects: [
          { kind: "max-health-percent", value: 25 },
          { kind: "attack-speed-percent", value: 18 },
        ],
        label: "+25% health, +18% attack speed",
      },
    ],
  },
  {
    id: "swordsman",
    name: "Swordsman",
    category: "role",
    description: "Blade users gain critical strike chance.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "critical-chance-percent", value: 18 }],
        label: "+18% critical chance",
      },
      {
        required: 3,
        effects: [{ kind: "critical-chance-percent", value: 38 }],
        label: "+38% critical chance",
      },
    ],
  },
  {
    id: "marksman",
    name: "Marksman",
    category: "role",
    description: "Ranged experts gain reach and precision.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "range-flat", value: 1 },
          { kind: "critical-chance-percent", value: 10 },
        ],
        label: "+1 range, +10% critical chance",
      },
      {
        required: 3,
        effects: [
          { kind: "range-flat", value: 2 },
          { kind: "critical-chance-percent", value: 20 },
        ],
        label: "+2 range, +20% critical chance",
      },
    ],
  },
  {
    id: "specialist",
    name: "Specialist",
    category: "role",
    description: "Technical fighters amplify their abilities.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "ability-power-percent", value: 20 }],
        label: "+20% ability power",
      },
      {
        required: 4,
        effects: [
          { kind: "ability-power-percent", value: 45 },
          { kind: "starting-energy", value: 15 },
        ],
        label: "+45% ability power, +15 energy",
      },
    ],
  },
  {
    id: "guardian",
    name: "Guardian",
    category: "role",
    description: "Frontliners begin protected and resist attacks.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "defense-flat", value: 15 },
          { kind: "shield-flat", value: 90 },
        ],
        label: "+15 defense, 90 shield",
      },
      {
        required: 3,
        effects: [
          { kind: "defense-flat", value: 32 },
          { kind: "shield-flat", value: 220 },
        ],
        label: "+32 defense, 220 shield",
      },
    ],
  },
];

const componentItem = (
  id: string,
  name: string,
  effects: ItemDefinition["effects"] = [],
  icon = "◇",
): ItemDefinition => ({
  id,
  name,
  description: "A core crafting component.",
  icon,
  kind: "component",
  effects,
});

const completedItem = (
  id: string,
  name: string,
  effects: ItemDefinition["effects"] = [],
  description = "A completed core item; its combat identity is reserved for P4B.",
  behaviors?: ItemDefinition["behaviors"],
  grantedTraitId?: string,
): ItemDefinition => ({
  id,
  name,
  description,
  icon: "◆",
  kind: "completed",
  effects,
  ...(behaviors ? { behaviors } : {}),
  ...(grantedTraitId ? { grantedTraitId } : {}),
});

export const COMPONENT_ITEM_DEFINITIONS: ItemDefinition[] = [
  componentItem("jolly-roger-fragment", "Jolly Roger Fragment", [], "☠"),
  componentItem("devil-fruit-essence", "Devil Fruit Essence", [
    { kind: "ability-power-percent", value: 10 },
  ], "✦"),
  componentItem("cola-canister", "Cola Canister", [
    { kind: "starting-energy", value: 15 },
  ], "◉"),
  componentItem("jet-dial", "Jet Dial", [
    { kind: "attack-speed-percent", value: 10 },
  ], "ϟ"),
  componentItem("sniper-lens", "Sniper Lens", [
    { kind: "critical-chance-percent", value: 10 },
  ], "◎"),
  componentItem("sea-king-meat", "Sea King Meat", [
    { kind: "health-flat", value: 45 },
  ], "♥"),
  componentItem("sea-prism-shard", "Sea-Prism Shard", [
    { kind: "special-defense-flat", value: 3 },
  ], "⛓"),
  componentItem("black-blade-shard", "Black Blade Shard", [
    { kind: "attack-flat", value: 9 },
  ], "†"),
  componentItem("armament-plate", "Armament Plate", [
    { kind: "defense-flat", value: 3 },
  ], "⛨"),
  componentItem("captains-sash", "Captain's Sash", [
    { kind: "shield-flat", value: 45 },
  ], "◆"),
];

const LEGACY_COMPLETED_ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: "black-blade",
    name: "Black Blade",
    description: "Grants 50% critical chance and 9 Attack.",
    icon: "†",
    kind: "completed",
    effects: [
      { kind: "critical-chance-percent", value: 50 },
      { kind: "attack-flat", value: 9 },
    ],
  },
  {
    id: "meat-platter",
    name: "Meat Platter",
    description: "Grants 300 Max HP and a starting shield equal to 20% of final starting Max HP.",
    icon: "✚",
    kind: "completed",
    effects: [
      { kind: "health-flat", value: 300 },
      { kind: "starting-shield-max-health-percent", value: 20 },
    ],
  },
  {
    id: "clima-tact",
    name: "Clima-Tact",
    description: "Every second, grants 5% ability power and 5 Energy.",
    icon: "ϟ",
    kind: "completed",
    effects: [],
    behaviors: [
      {
        kind: "periodic-ability-power-energy",
        intervalMs: 1_000,
        abilityPowerPercent: 5,
        energy: 5,
      },
    ],
  },
  {
    id: "sniper-goggles",
    name: "Sniper Goggles",
    description: "Grants 2 Range, 15% critical chance, and 3 Special Defense.",
    icon: "◎",
    kind: "completed",
    effects: [
      { kind: "range-flat", value: 2 },
      { kind: "critical-chance-percent", value: 15 },
      { kind: "special-defense-flat", value: 3 },
    ],
  },
  {
    id: "sea-prism-stone",
    name: "Sea Prism Stone",
    description: "Grants 40 Special Defense and halves Burn tick damage.",
    icon: "◆",
    kind: "completed",
    effects: [{ kind: "special-defense-flat", value: 40 }],
    behaviors: [{ kind: "burn-damage-reduction-percent", percent: 50 }],
  },
  {
    id: "armament-wraps",
    name: "Armament Wraps",
    description: "Grants 10% attack speed and 3 Defense. Every second positive damage event grants 3 Attack, 2 Defense, and 5% attack speed, up to ten times.",
    icon: "◈",
    kind: "completed",
    effects: [
      { kind: "attack-speed-percent", value: 10 },
      { kind: "defense-flat", value: 3 },
    ],
    behaviors: [
      {
        kind: "on-damage-received-stack",
        maxEvents: 20,
        eventsPerProc: 2,
        attack: 3,
        defense: 2,
        attackSpeedPercent: 5,
      },
    ],
  },
  {
    id: "den-den-mushi",
    name: "Den Den Mushi",
    description: "Grants 15 starting Energy and 10% attack speed. Every third basic attack chains 30 Special damage and drains 15 Energy from up to two closest enemies.",
    icon: "☏",
    kind: "completed",
    effects: [
      { kind: "starting-energy", value: 15 },
      { kind: "attack-speed-percent", value: 10 },
    ],
    behaviors: [
      {
        kind: "every-n-basic-attacks-chain",
        every: 3,
        targets: 2,
        specialDamage: 30,
        energyDrain: 15,
      },
    ],
  },
  {
    id: "cola-engine",
    name: "Cola Engine",
    description: "Grants 10% ability power and attack speed, then 5% attack speed after every basic attack.",
    icon: "⚙",
    kind: "completed",
    effects: [
      { kind: "ability-power-percent", value: 10 },
      { kind: "attack-speed-percent", value: 10 },
    ],
    behaviors: [
      {
        kind: "on-basic-attack-attack-speed",
        attackSpeedPercent: 5,
      },
    ],
  },
];

const NEW_COMPLETED_ITEM_DEFINITIONS: ItemDefinition[] = [
  completedItem("emperors-jolly-roger", "Emperor's Jolly Roger", [], "Grants Emperor.", undefined, "emperor"),
  completedItem("specialists-log-pose", "Specialist's Log Pose", [{ kind: "ability-power-percent", value: 20 }], "Grants Specialist and 20% ability power.", undefined, "specialist"),
  completedItem("marine-justice-coat", "Marine Justice Coat", [{ kind: "starting-energy", value: 30 }], "Grants Navy and 30 starting Energy.", undefined, "navy"),
  completedItem("marksmans-thunder-dial", "Marksman's Thunder Dial", [{ kind: "attack-speed-percent", value: 20 }], "Grants Marksman and 20% attack speed.", undefined, "marksman"),
  completedItem("captains-logbook", "Captain's Logbook", [{ kind: "critical-chance-percent", value: 20 }], "Grants Captain and 20% critical chance.", undefined, "captain"),
  completedItem("brawlers-rumble-emblem", "Brawler's Rumble Emblem", [{ kind: "health-flat", value: 90 }], "Grants Brawler and 90 Health.", undefined, "brawler"),
  completedItem("guardians-sea-prism-crest", "Guardian's Sea-Prism Crest", [{ kind: "special-defense-flat", value: 6 }], "Grants Guardian and 6 Special Defense.", undefined, "guardian"),
  completedItem("revolutionary-flame", "Revolutionary Flame", [{ kind: "attack-flat", value: 18 }], "Grants Revolutionary and 18 Attack.", undefined, "revolutionary"),
  completedItem("straw-hat-token", "Straw Hat Token", [{ kind: "defense-flat", value: 6 }], "Grants Straw Hat and 6 Defense.", undefined, "straw-hat"),
  completedItem("swordsmans-knot", "Swordsman's Knot", [{ kind: "shield-flat", value: 90 }], "Grants Swordsman and 90 Shield.", undefined, "swordsman"),
  completedItem(
    "devil-fruit-codex",
    "Devil Fruit Codex",
    [{ kind: "ability-power-percent", value: 100 }],
    "Grants 100% ability power.",
  ),
  completedItem(
    "observation-haki-mantle",
    "Observation Haki Mantle",
    [
      { kind: "ability-power-percent", value: 10 },
      { kind: "critical-chance-percent", value: 20 },
      { kind: "ability-crit" },
    ],
    "Grants 10% ability power and 20% critical chance; abilities can crit. Natively critical abilities grant 50% Crit Power at battle start.",
    [{ kind: "native-ability-crit-power", criticalPowerPercent: 50 }],
  ),
  completedItem(
    "barrier-bubble",
    "Barrier Bubble",
    [{ kind: "ability-power-percent", value: 10 }],
    "Grants 10% ability power. At battle start, the holder and horizontal allies gain Shield equal to 20% of their own final Max HP and Rune Protect for 5 seconds.",
    [{
      kind: "start-horizontal-shield-rune-protect",
      shieldMaxHealthPercent: 20,
      runeProtectMs: 5_000,
    }],
  ),
  completedItem(
    "reflect-dial",
    "Reflect Dial",
    [
      { kind: "special-defense-flat", value: 10 },
      { kind: "ability-power-percent", value: 10 },
    ],
    "Grants 10 Special Defense and 10% ability power. Reflects Special damage prevented by resistance.",
    [{ kind: "reflect-special-resistance-blocked" }],
  ),
  completedItem(
    "flame-flame-grimoire",
    "Flame-Flame Grimoire",
    [
      { kind: "ability-power-percent", value: 30 },
      { kind: "attack-flat", value: 9 },
    ],
    "Grants 30% ability power and 9 Attack. Positive Special damage burns for 3 seconds and reduces the target's Special Defense by 1.",
    [{
      kind: "on-special-damage-burn-resistance",
      burnDurationMs: 3_000,
      specialDefenseDelta: -1,
    }],
  ),
  completedItem(
    "sea-prism-boots",
    "Sea-Prism Boots",
    [
      { kind: "ability-power-percent", value: 50 },
      { kind: "defense-flat", value: 12 },
    ],
    "Grants 50% ability power and 12 Defense. Enemy knockback and pull cannot move the holder.",
    [{ kind: "forced-movement-immunity" }],
  ),
  completedItem(
    "lucky-pirate-ribbon",
    "Lucky Pirate Ribbon",
    [
      { kind: "shield-flat", value: 45 },
      { kind: "ability-power-percent", value: 50 },
      { kind: "luck-flat", value: 20 },
      { kind: "dodge-percent", value: 15 },
    ],
    "Grants 45 Shield, 50% ability power, 20 Luck, and 15% Dodge.",
  ),
  completedItem(
    "cola-reservoir",
    "Cola Reservoir",
    [{ kind: "starting-energy", value: 30 }],
    "Grants 30 starting Energy. After each cast, restores 20 plus 2 Energy per cast, up to 90.",
    [{
      kind: "on-ability-cast-energy",
      baseEnergy: 20,
      perCastEnergy: 2,
      maxEnergy: 90,
    }],
  ),
  completedItem(
    "energy-siphon-scope",
    "Energy-Siphon Scope",
    [
      { kind: "starting-energy", value: 15 },
      { kind: "critical-chance-percent", value: 25 },
    ],
    "Grants 15 starting Energy and 25% critical chance; critical basic attacks steal up to 10 Energy.",
    [{ kind: "on-critical-basic-attack-energy-steal", amount: 10 }],
  ),
  completedItem(
    "healing-bubble",
    "Healing Bubble",
    [{ kind: "health-flat", value: 45 }],
    "Grants 45 Max HP. Every 2 seconds, heals the holder and adjacent allies for 5% of their own Max HP and converts 10% of overheal to Energy.",
    [{
      kind: "periodic-adjacent-heal-overheal-energy",
      intervalMs: 2_000,
      healMaxHealthPercent: 5,
      overhealEnergyPercent: 10,
    }],
  ),
  completedItem(
    "star-shield-dial",
    "Star Shield Dial",
    [
      { kind: "special-defense-flat", value: 10 },
      { kind: "starting-energy", value: 15 },
    ],
    "Grants 10 Special Defense and 15 starting Energy; grants 50 Shield after each cast.",
    [{ kind: "on-ability-cast-shield", shield: 50 }],
  ),
  completedItem(
    "shark-tooth-charm",
    "Shark Tooth Charm",
    [
      { kind: "attack-flat", value: 21 },
      { kind: "starting-energy", value: 15 },
    ],
    "Grants 21 Attack and 15 starting Energy; basic attacks grant 5 Energy plus 15 on a kill.",
    [
      {
        kind: "on-basic-attack-energy",
        energy: 5,
        killBonusEnergy: 15,
      },
    ],
  ),
  completedItem(
    "miracle-talisman",
    "Miracle Talisman",
    [{ kind: "defense-flat", value: 3 }],
    "Grants 3 Defense. Once per battle, damage that would leave the holder below 30% health is cancelled after Shield, grants 50 Energy, and applies Protect for 1.5 seconds.",
    [{
      kind: "low-health-protect-energy",
      healthThresholdPercent: 30,
      energy: 50,
      protectMs: 1_500,
    }],
  ),
  completedItem(
    "efficient-bandanna",
    "Efficient Bandanna",
    [
      { kind: "shield-flat", value: 45 },
      { kind: "starting-energy", value: 15 },
    ],
    "Grants 45 Shield and 15 starting Energy. At battle start, the holder and horizontal allies have 15% lower Max Energy.",
    [{ kind: "start-horizontal-max-energy", percent: 85 }],
  ),
  completedItem(
    "observation-goggles",
    "Observation Goggles",
    [{ kind: "attack-speed-percent", value: 50 }],
    "Grants 50% attack speed and makes basic attacks impossible to dodge.",
    [{ kind: "basic-attacks-cannot-miss" }],
  ),
  completedItem(
    "armor-piercing-scope",
    "Armor-Piercing Scope",
    [
      { kind: "attack-speed-percent", value: 10 },
      { kind: "critical-chance-percent", value: 10 },
      { kind: "critical-power-percent", value: 50 },
    ],
    "Grants 10% attack speed, 10% critical chance, and 50% Crit Power. Successful basic attacks halve both resistances for 2 seconds before dealing damage.",
    [{ kind: "on-basic-attack-resistance-reduction", durationMs: 2_000 }],
  ),
  completedItem(
    "rush-flag",
    "Rush Flag",
    [],
    "At battle start, the holder and horizontal allies gain 20% attack speed as part of their dynamic baseline.",
    [{ kind: "start-horizontal-attack-speed", attackSpeedPercent: 20 }],
  ),
  completedItem(
    "ricochet-dial",
    "Ricochet Dial",
    [
      { kind: "attack-speed-percent", value: 10 },
      { kind: "special-defense-flat", value: 3 },
      { kind: "luck-flat", value: 20 },
    ],
    "Grants 10% attack speed, 3 Special Defense, and 20 Luck. Basic attacks can bounce 75% of each raw damage component to an adjacent enemy.",
    [{ kind: "on-basic-attack-bounce", chancePercent: 50, damagePercent: 75 }],
  ),
  completedItem(
    "impact-dial",
    "Impact Dial",
    [
      { kind: "attack-speed-percent", value: 10 },
      { kind: "attack-flat", value: 9 },
    ],
    "Grants 10% attack speed and 9 Attack. Basic attacks add 8% of the target's Max HP as Physical damage, including when dodged.",
    [{ kind: "on-basic-attack-target-max-health-physical", percent: 8 }],
  ),
  completedItem(
    "jet-sash",
    "Jet Sash",
    [
      { kind: "shield-flat", value: 45 },
      { kind: "attack-speed-percent", value: 10 },
    ],
    "Grants 45 Shield and 10% attack speed, then 20% attack speed every 3 seconds.",
    [
      {
        kind: "periodic-attack-speed",
        intervalMs: 3_000,
        attackSpeedPercent: 20,
      },
    ],
  ),
  completedItem(
    "mystery-treasure-chest",
    "Mystery Treasure Chest",
    [],
    "At battle start, replaces itself with up to two distinct seeded non-trait completed items for that battle only.",
    [{ kind: "battle-random-items", rolls: 2 }],
  ),
  completedItem(
    "smoke-star-escape",
    "Smoke-Star Escape",
    [{ kind: "critical-chance-percent", value: 10 }],
    "Grants 10% critical chance. Once below 40% health, Blinds and Paralyzes adjacent enemies for 4 seconds, grants 150 Shield, and escapes.",
    [{
      kind: "low-health-smoke-escape",
      healthThresholdPercent: 40,
      statusMs: 4_000,
      shield: 150,
    }],
  ),
  completedItem(
    "gas-mask",
    "Gas Mask",
    [
      { kind: "critical-chance-percent", value: 10 },
      { kind: "defense-flat", value: 3 },
    ],
    "Grants 10% critical chance and 3 Defense, plus Rune Protect for 60 seconds at battle start.",
    [{ kind: "starting-rune-protect", durationMs: 60_000 }],
  ),
  completedItem(
    "armament-sash",
    "Armament Sash",
    [
      { kind: "shield-flat", value: 45 },
      { kind: "critical-chance-percent", value: 30 },
    ],
    "Grants 45 Shield and 30% critical chance. Critical basic attacks grant Shield equal to 33% of the complete raw primary damage, rounded up.",
    [{ kind: "on-critical-basic-attack-shield-damage-percent", percent: 33 }],
  ),
  completedItem(
    "spiked-armament",
    "Spiked Armament",
    [
      { kind: "defense-flat", value: 6 },
      { kind: "health-flat", value: 45 },
    ],
    "Grants 6 Defense and 45 Max HP. Adjacent basic attackers take Defense-scaled True retaliation damage and Wound for 3 seconds.",
    [{ kind: "on-basic-attack-received-retaliate-wound", woundMs: 3_000 }],
  ),
  completedItem(
    "impact-proof-gauntlets",
    "Impact-Proof Gauntlets",
    [
      { kind: "shield-flat", value: 180 },
      { kind: "attack-flat", value: 18 },
    ],
    "Grants 180 Shield and 18 Attack. Damage entering an enemy Shield is doubled, and retaliation is suppressed.",
    [{
      kind: "shield-damage-multiplier",
      multiplierPercent: 200,
      suppressRetaliation: true,
    }],
  ),
  completedItem(
    "phoenix-feather",
    "Phoenix Feather",
    [],
    "Once per battle, enters a 2-second resurrection instead of dying and returns with battle-start stats and full health.",
    [{ kind: "resurrect-once", delayMs: 2_000 }],
  ),
  completedItem(
    "banquet-belt",
    "Banquet Belt",
    [
      { kind: "health-flat", value: 150 },
      { kind: "shield-flat", value: 45 },
    ],
    "Grants 150 Max HP and 45 Shield. Supported combat stat buffs and friendly buff losses are 25% stronger.",
    [{ kind: "combat-stat-delta-amplifier", percent: 25 }],
  ),
  completedItem(
    "healing-dial",
    "Healing Dial",
    [
      { kind: "attack-flat", value: 15 },
      { kind: "special-defense-flat", value: 5 },
    ],
    "Grants 15 Attack and 5 Special Defense; heals for 33% of damage dealt to others, including shield damage, rounded up.",
    [{ kind: "on-damage-dealt-heal-percent", percent: 33 }],
  ),
  completedItem(
    "guard-point-dummy",
    "Guard Point Dummy",
    [
      { kind: "defense-flat", value: 3 },
      { kind: "special-defense-flat", value: 3 },
    ],
    "Grants 3 Defense and 3 Special Defense, reduces incoming non-True damage by 30%, and wins tied nearest basic-attack targeting.",
    [{
      kind: "incoming-nontrue-damage-reduction-percent",
      percent: 30,
      basicAttackTargetPriority: true,
    }],
  ),
  completedItem(
    "reversal-band",
    "Reversal Band",
    [
      { kind: "special-defense-flat", value: 20 },
      { kind: "shield-flat", value: 150 },
    ],
    "Grants 20 Special Defense and 150 Shield. Supported negative enemy or environment combat stat deltas become positive.",
    [{ kind: "enemy-debuff-inversion" }],
  ),
  completedItem(
    "advanced-armament-orb",
    "Advanced Armament Orb",
    [{ kind: "attack-flat", value: 30 }],
    "Grants 30 Attack and converts 25% of normal basic-attack damage to True damage.",
    [{ kind: "basic-attack-true-damage-percent", percent: 25 }],
  ),
  completedItem(
    "mera-mera-ember",
    "Mera Mera Ember",
    [
      { kind: "attack-flat", value: 15 },
      { kind: "defense-flat", value: 3 },
    ],
    "Grants 15 Attack and 3 Defense, adds the holder's star-scaled base Attack at battle start, and self-applies a battle-long Burn.",
    [{ kind: "start-base-attack-self-burn", burnDurationMs: 300_000 }],
  ),
  completedItem(
    "bombardier-band",
    "Bombardier Band",
    [
      { kind: "shield-flat", value: 150 },
      { kind: "attack-flat", value: 9 },
    ],
    "Grants 150 Shield and 9 Attack. The first Shield depletion explodes for half of runtime Shield gained as adjacent Special damage.",
    [{ kind: "shield-depletion-explosion", percent: 50 }],
  ),
  completedItem(
    "iron-pirate-helm",
    "Iron Pirate Helm",
    [{ kind: "defense-flat", value: 25 }],
    "Grants 25 Defense and negates incoming critical bonus damage while preserving critical-hit identity.",
    [{ kind: "incoming-critical-bonus-negation" }],
  ),
  completedItem(
    "bodyguard-band",
    "Bodyguard Band",
    [
      { kind: "defense-flat", value: 12 },
      { kind: "shield-flat", value: 150 },
    ],
    "Grants 12 Defense and 150 Shield. Intercepts lethal post-Shield damage for one adjacent ally.",
    [{ kind: "lethal-cover" }],
  ),
  completedItem(
    "nullification-bandanna",
    "Nullification Bandanna",
    [{ kind: "shield-flat", value: 90 }],
    "Grants 90 Shield. Cannot cast, converts Ability Power deltas into Attack, and spends stored Energy as Special damage on basic attacks.",
    [{ kind: "cannot-cast-energy-attacks", attackConversionPercent: 60 }],
  ),
];

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  ...LEGACY_COMPLETED_ITEM_DEFINITIONS,
  ...COMPONENT_ITEM_DEFINITIONS,
  ...NEW_COMPLETED_ITEM_DEFINITIONS,
];

const ITEM_RECIPE_TUPLES = [
  ["jolly-roger-fragment", "jolly-roger-fragment", "emperors-jolly-roger"],
  ["jolly-roger-fragment", "devil-fruit-essence", "specialists-log-pose"],
  ["jolly-roger-fragment", "cola-canister", "marine-justice-coat"],
  ["jolly-roger-fragment", "jet-dial", "marksmans-thunder-dial"],
  ["jolly-roger-fragment", "sniper-lens", "captains-logbook"],
  ["jolly-roger-fragment", "sea-king-meat", "brawlers-rumble-emblem"],
  ["jolly-roger-fragment", "sea-prism-shard", "guardians-sea-prism-crest"],
  ["jolly-roger-fragment", "black-blade-shard", "revolutionary-flame"],
  ["jolly-roger-fragment", "armament-plate", "straw-hat-token"],
  ["jolly-roger-fragment", "captains-sash", "swordsmans-knot"],
  ["devil-fruit-essence", "devil-fruit-essence", "devil-fruit-codex"],
  ["devil-fruit-essence", "cola-canister", "clima-tact"],
  ["devil-fruit-essence", "jet-dial", "cola-engine"],
  ["devil-fruit-essence", "sniper-lens", "observation-haki-mantle"],
  ["devil-fruit-essence", "sea-king-meat", "barrier-bubble"],
  ["devil-fruit-essence", "sea-prism-shard", "reflect-dial"],
  ["devil-fruit-essence", "black-blade-shard", "flame-flame-grimoire"],
  ["devil-fruit-essence", "armament-plate", "sea-prism-boots"],
  ["devil-fruit-essence", "captains-sash", "lucky-pirate-ribbon"],
  ["cola-canister", "cola-canister", "cola-reservoir"],
  ["cola-canister", "jet-dial", "den-den-mushi"],
  ["cola-canister", "sniper-lens", "energy-siphon-scope"],
  ["cola-canister", "sea-king-meat", "healing-bubble"],
  ["cola-canister", "sea-prism-shard", "star-shield-dial"],
  ["cola-canister", "black-blade-shard", "shark-tooth-charm"],
  ["cola-canister", "armament-plate", "miracle-talisman"],
  ["cola-canister", "captains-sash", "efficient-bandanna"],
  ["jet-dial", "jet-dial", "observation-goggles"],
  ["jet-dial", "sniper-lens", "armor-piercing-scope"],
  ["jet-dial", "sea-king-meat", "rush-flag"],
  ["jet-dial", "sea-prism-shard", "ricochet-dial"],
  ["jet-dial", "black-blade-shard", "impact-dial"],
  ["jet-dial", "armament-plate", "armament-wraps"],
  ["jet-dial", "captains-sash", "jet-sash"],
  ["sniper-lens", "sniper-lens", "mystery-treasure-chest"],
  ["sniper-lens", "sea-king-meat", "smoke-star-escape"],
  ["sniper-lens", "sea-prism-shard", "sniper-goggles"],
  ["sniper-lens", "black-blade-shard", "black-blade"],
  ["sniper-lens", "armament-plate", "gas-mask"],
  ["sniper-lens", "captains-sash", "armament-sash"],
  ["sea-king-meat", "sea-king-meat", "meat-platter"],
  ["sea-king-meat", "sea-prism-shard", "phoenix-feather"],
  ["sea-king-meat", "black-blade-shard", "impact-proof-gauntlets"],
  ["sea-king-meat", "armament-plate", "spiked-armament"],
  ["sea-king-meat", "captains-sash", "banquet-belt"],
  ["sea-prism-shard", "sea-prism-shard", "sea-prism-stone"],
  ["sea-prism-shard", "black-blade-shard", "healing-dial"],
  ["sea-prism-shard", "armament-plate", "guard-point-dummy"],
  ["sea-prism-shard", "captains-sash", "reversal-band"],
  ["black-blade-shard", "black-blade-shard", "advanced-armament-orb"],
  ["black-blade-shard", "armament-plate", "mera-mera-ember"],
  ["black-blade-shard", "captains-sash", "bombardier-band"],
  ["armament-plate", "armament-plate", "iron-pirate-helm"],
  ["armament-plate", "captains-sash", "bodyguard-band"],
  ["captains-sash", "captains-sash", "nullification-bandanna"],
] as const;

export const ITEM_RECIPES: Record<string, string> = Object.fromEntries(
  ITEM_RECIPE_TUPLES.map(([firstId, secondId, resultId]) => [
    canonicalItemRecipeKey(firstId, secondId),
    resultId,
  ]),
);

export const ACQUIRABLE_ITEM_IDS = [
  "jolly-roger-fragment",
  "devil-fruit-essence",
  "cola-canister",
  "jet-dial",
  "sniper-lens",
  "sea-king-meat",
  "sea-prism-shard",
  "black-blade-shard",
  "armament-plate",
  "captains-sash",
];

const basicEnemyAbility = (
  id: string,
  name: string,
  power: number,
): UnitDefinition["ability"] =>
  ability(id, name, `${name} damages its target.`, power, "nearest-enemy", "single");

export const PVE_ENEMY_DEFINITIONS: PvEEnemyDefinition[] = [
  {
    id: "marine-recruit",
    name: "Marine Recruit",
    stats: {
      health: 420,
      attack: 38,
      defense: 10,
      range: 1,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    assetPath: "/assets/enemies/marine-recruit.png",
  },
  {
    id: "rifle-marine",
    name: "Rifle Marine",
    stats: {
      health: 380,
      attack: 48,
      defense: 8,
      range: 5,
      attackIntervalMs: 1_400,
      moveIntervalMs: 500,
    },
    ability: basicEnemyAbility("rifle-volley", "Rifle Volley", 110),
    assetPath: "/assets/enemies/rifle-marine.png",
  },
  {
    id: "pirate-raider",
    name: "Pirate Raider",
    stats: {
      health: 600,
      attack: 62,
      defense: 16,
      range: 1,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: basicEnemyAbility("reckless-slash", "Reckless Slash", 145),
    assetPath: "/assets/enemies/pirate-raider.png",
  },
  {
    id: "sea-king",
    name: "Sea King",
    stats: {
      health: 1_600,
      attack: 88,
      defense: 28,
      range: 2,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: {
      ...basicEnemyAbility("tidal-roar", "Tidal Roar", 190),
      pattern: "adjacent",
      stunMs: 600,
    },
    assetPath: "/assets/enemies/sea-king.png",
  },
  {
    id: "pacifista",
    name: "Pacifista",
    stats: {
      health: 2_100,
      attack: 105,
      defense: 38,
      range: 5,
      attackIntervalMs: 1_400,
      moveIntervalMs: 600,
    },
    ability: {
      ...basicEnemyAbility("laser-beam", "Laser Beam", 285),
      pattern: "line",
    },
    assetPath: "/assets/enemies/pacifista.png",
  },
  {
    id: "vice-admiral",
    name: "Vice Admiral",
    stats: {
      health: 3_200,
      attack: 130,
      defense: 45,
      specialDefense: 35,
      range: 1,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "haki-shockwave",
      "Haki Shockwave",
      "Strikes the nearest enemy and adjacent foes with a physical Haki shockwave.",
      360,
      "nearest-enemy",
      "adjacent",
      { damageType: "physical", stunMs: 500 },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "cipher-pol-agent",
    name: "Cipher Pol Agent",
    stats: {
      health: 2_800,
      attack: 150,
      defense: 38,
      specialDefense: 38,
      range: 1,
      attackIntervalMs: 800,
      moveIntervalMs: 350,
    },
    ability: ability(
      "six-powers-assault",
      "Six Powers Assault",
      "Lunges at the nearest enemy with a Defense-piercing physical assault.",
      420,
      "nearest-enemy",
      "single",
      {
        damageType: "physical",
        requiresTarget: false,
        defensePiercePercent: 25,
        signatureMechanics: [{ kind: "lunge" }],
      },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
  {
    id: "seraphim",
    name: "Seraphim",
    stats: {
      health: 4_200,
      attack: 140,
      defense: 60,
      specialDefense: 55,
      range: 4,
      attackIntervalMs: 1_100,
      moveIntervalMs: 450,
    },
    ability: ability(
      "lunarian-laser",
      "Lunarian Laser",
      "Burns a line through the farthest enemy with a special Lunarian laser.",
      400,
      "farthest-enemy",
      "line",
      {
        damageType: "special",
        burnPower: 20,
        burnDurationMs: 3_000,
      },
    ),
    assetPath: "/assets/characters/placeholder.svg",
  },
];

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    id: "east-blue-patrol",
    round: 1,
    kind: "pve",
    name: "East Blue Patrol",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [{ enemyId: "marine-recruit", count: 2 }],
    itemChoices: 3,
  },
  {
    id: "rifle-line",
    round: 2,
    kind: "pve",
    name: "Rifle Line",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "marine-recruit", count: 2 },
      { enemyId: "rifle-marine", count: 1 },
    ],
    itemChoices: 3,
  },
  {
    id: "raider-ambush",
    round: 3,
    kind: "pve",
    name: "Raider Ambush",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "marine-recruit", count: 2 },
      { enemyId: "pirate-raider", count: 1 },
    ],
    itemChoices: 3,
  },
  {
    id: "first-muster",
    round: 4,
    kind: "carousel",
    name: "First Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "calm-belt",
    round: 9,
    kind: "pve",
    name: "Calm Belt",
    preparationSeconds: 40,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "sea-king", count: 1 },
      { enemyId: "pirate-raider", count: 2 },
    ],
    itemChoices: 3,
  },
  {
    id: "grand-line-muster",
    round: 12,
    kind: "carousel",
    name: "Grand Line Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "pacifista-test",
    round: 14,
    kind: "pve",
    name: "Pacifista Test",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "pacifista", count: 1 },
      { enemyId: "rifle-marine", count: 2 },
    ],
    itemChoices: 3,
  },
  {
    id: "new-world-muster",
    round: 17,
    kind: "carousel",
    name: "New World Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "siege-of-justice",
    round: 19,
    kind: "pve",
    name: "Siege of Justice",
    preparationSeconds: 40,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "pacifista", count: 2 },
      { enemyId: "sea-king", count: 1 },
    ],
    itemChoices: 3,
  },
  {
    id: "new-world-exchange",
    round: 22,
    kind: "carousel",
    name: "New World Exchange",
    preparationSeconds: 30,
    battleSeconds: 45,
    rewardItemKind: "completed",
  },
  {
    id: "vice-admiral-vanguard",
    round: 24,
    kind: "pve",
    name: "Vice Admiral Vanguard",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [{ enemyId: "vice-admiral", count: 3 }],
    itemChoices: 3,
    rewardItemKind: "completed",
  },
  {
    id: "emperors-crossroads",
    round: 27,
    kind: "carousel",
    name: "Emperor's Crossroads",
    preparationSeconds: 30,
    battleSeconds: 45,
    rewardItemKind: "completed",
  },
  {
    id: "cipher-pol-hunt",
    round: 28,
    kind: "pve",
    name: "Cipher Pol Hunt",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [{ enemyId: "cipher-pol-agent", count: 3 }],
    itemChoices: 3,
    rewardItemKind: "completed",
  },
  {
    id: "seraphim-deployment",
    round: 32,
    kind: "pve",
    name: "Seraphim Deployment",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [{ enemyId: "seraphim", count: 3 }],
    itemChoices: 3,
    rewardItemKind: "completed",
  },
  {
    id: "final-voyage-muster",
    round: 34,
    kind: "carousel",
    name: "Final Voyage Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
    rewardItemKind: "completed",
  },
  {
    id: "world-government-onslaught",
    round: 36,
    kind: "pve",
    name: "World Government Onslaught",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "vice-admiral", count: 2 },
      { enemyId: "cipher-pol-agent", count: 2 },
      { enemyId: "seraphim", count: 2 },
    ],
    itemChoices: 3,
    rewardItemKind: "completed",
  },
];

export const BOT_PERSONALITIES: BotPersonality[] = [
  {
    id: "balanced",
    name: "Balanced",
    economyReserve: 10,
    levelAggression: 0.55,
    rerollAggression: 0.45,
    preferredTraits: [],
    formation: "spread",
  },
  {
    id: "treasurer",
    name: "Treasurer",
    economyReserve: 25,
    levelAggression: 0.35,
    rerollAggression: 0.2,
    preferredTraits: ["straw-hat", "captain"],
    formation: "corner",
  },
  {
    id: "high-roller",
    name: "High Roller",
    economyReserve: 5,
    levelAggression: 0.3,
    rerollAggression: 0.9,
    preferredTraits: ["supernova", "swordsman"],
    formation: "frontline",
  },
  {
    id: "vanguard",
    name: "Vanguard",
    economyReserve: 8,
    levelAggression: 0.85,
    rerollAggression: 0.25,
    preferredTraits: ["navy", "guardian"],
    formation: "frontline",
  },
  {
    id: "strategist",
    name: "Strategist",
    economyReserve: 15,
    levelAggression: 0.6,
    rerollAggression: 0.5,
    preferredTraits: ["specialist", "warlord"],
    formation: "corner",
  },
  {
    id: "sharpshooter",
    name: "Sharpshooter",
    economyReserve: 12,
    levelAggression: 0.5,
    rerollAggression: 0.55,
    preferredTraits: ["marksman", "revolutionary"],
    formation: "corner",
  },
  {
    id: "brawler",
    name: "Brawler",
    economyReserve: 7,
    levelAggression: 0.65,
    rerollAggression: 0.65,
    preferredTraits: ["brawler", "brotherhood"],
    formation: "frontline",
  },
];

export const GAME_CONFIG: GameConfig = {
  boardWidth: 8,
  boardHeight: 6,
  deployRows: 3,
  benchSize: 8,
  shopSize: 6,
  itemCap: 3,
  playerCount: 8,
  startHealth: 100,
  startGold: 5,
  startLevel: 2,
  maxLevel: 9,
  rerollCost: 1,
  buyXpCost: 4,
  buyXpAmount: 4,
  autoXpPerRound: 2,
  baseIncome: 5,
  maxInterest: 5,
  maxStreakBonus: 5,
  pvpWinGold: 1,
  poolCopiesByCost: [27, 22, 18, 14, 10],
  shopOddsByLevel: {
    "2": [1, 0, 0, 0, 0],
    "3": [0.7, 0.3, 0, 0, 0],
    "4": [0.5, 0.4, 0.1, 0, 0],
    "5": [0.36, 0.42, 0.2, 0.02, 0],
    "6": [0.25, 0.4, 0.3, 0.05, 0],
    "7": [0.16, 0.33, 0.35, 0.15, 0.01],
    "8": [0.11, 0.27, 0.35, 0.22, 0.05],
    "9": [0.05, 0.2, 0.35, 0.3, 0.1],
  },
  xpToNextByLevel: {
    "2": 2,
    "3": 6,
    "4": 10,
    "5": 22,
    "6": 34,
    "7": 52,
    "8": 72,
  },
  starStatBasisPoints: [10_000, 18_000, 32_400],
  starAbilityBasisPoints: [10_000, 15_000, 22_500],
  combatTickMs: 100,
  combatMaxTicks: 450,
  recordBattleEvents: true,
};

export const DEFAULT_CONTENT: GameContent = {
  version: "1.24.0",
  units: UNIT_DEFINITIONS,
  forms: FORM_DEFINITIONS,
  traits: TRAIT_DEFINITIONS,
  items: ITEM_DEFINITIONS,
  itemRecipes: ITEM_RECIPES,
  acquirableItemIds: ACQUIRABLE_ITEM_IDS,
  enemies: PVE_ENEMY_DEFINITIONS,
  stages: STAGE_DEFINITIONS,
  botPersonalities: BOT_PERSONALITIES,
  config: GAME_CONFIG,
};

export const CONTENT = DEFAULT_CONTENT;

export function getUnitDefinition(
  id: string,
  content: Pick<GameContent, "units"> = DEFAULT_CONTENT,
): UnitDefinition | null {
  return content.units.find((unit) => unit.id === id) ?? null;
}

export function getTraitDefinition(
  id: string,
  content: Pick<GameContent, "traits"> = DEFAULT_CONTENT,
): TraitDefinition | null {
  return content.traits.find((trait) => trait.id === id) ?? null;
}

export function getItemDefinition(
  id: string,
  content: Pick<GameContent, "items"> = DEFAULT_CONTENT,
): ItemDefinition | null {
  return content.items.find((item) => item.id === id) ?? null;
}

export function getStageDefinition(
  round: number,
  content: GameContent = DEFAULT_CONTENT,
): StageDefinition {
  const preparationSecondsByRound: Record<string, number> = {
    "1": 20,
    "2": 20,
    "3": 20,
    "5": 40,
    "8": 40,
    "9": 40,
    "10": 50,
    "11": 40,
    "15": 40,
    "19": 40,
    "20": 50,
  };
  return (
    content.stages.find((stage) => stage.round === round) ?? {
      id: `pvp-${round}`,
      round,
      kind: "pvp",
      name: `Rival Battle ${round}`,
      preparationSeconds: preparationSecondsByRound[String(round)] ?? 30,
      battleSeconds: 45,
    }
  );
}
