import type {
  BotPersonality,
  GameConfig,
  GameContent,
  ItemDefinition,
  PvEEnemyDefinition,
  StageDefinition,
  TraitDefinition,
  UnitDefinition,
} from "./types";

const ability = (
  id: string,
  name: string,
  description: string,
  power: number,
  targeting: UnitDefinition["ability"]["targeting"],
  pattern: UnitDefinition["ability"]["pattern"],
  extras: Partial<UnitDefinition["ability"]> = {},
): UnitDefinition["ability"] => ({
  id,
  name,
  description,
  targeting,
  pattern,
  effect: "damage",
  power,
  castAnimationMs: 500,
  ...extras,
});

export const UNIT_DEFINITIONS: UnitDefinition[] = [
  {
    id: "nami",
    name: "Nami",
    cost: 1,
    traits: ["straw-hat", "specialist"],
    stats: {
      health: 520,
      attack: 42,
      defense: 12,
      range: 4,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: ability(
      "thunderbolt-tempo",
      "Thunderbolt Tempo",
      "Calls lightning onto the target and nearby enemies.",
      145,
      "nearest-enemy",
      "adjacent",
    ),
    assetPath: "/assets/characters/nami.png",
  },
  {
    id: "usopp",
    name: "Usopp",
    cost: 1,
    traits: ["straw-hat", "marksman"],
    stats: {
      health: 500,
      attack: 52,
      defense: 10,
      range: 5,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "exploding-star",
      "Exploding Star",
      "Fires an explosive shot at the farthest enemy, damaging nearby enemies and blasting surviving targets backward.",
      160,
      "farthest-enemy",
      "adjacent",
      { signatureMechanics: [{ kind: "knockback" }] },
    ),
    assetPath: "/assets/characters/usopp.png",
  },
  {
    id: "chopper",
    name: "Chopper",
    cost: 1,
    traits: ["straw-hat", "guardian"],
    stats: {
      health: 650,
      attack: 38,
      defense: 18,
      range: 2,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: {
      ...ability(
        "emergency-cure",
        "Emergency Cure",
        "Restores health to the most injured ally.",
        220,
        "lowest-health-ally",
        "single-ally",
      ),
      effect: "heal",
      requiresTarget: false,
    },
    assetPath: "/assets/characters/chopper.png",
  },
  {
    id: "tashigi",
    name: "Tashigi",
    cost: 1,
    traits: ["navy", "swordsman"],
    stats: {
      health: 600,
      attack: 58,
      defense: 18,
      range: 1,
      attackIntervalMs: 1_100,
      moveIntervalMs: 400,
    },
    ability: ability(
      "flash-cut",
      "Flash Cut",
      "Lunges beside the nearest enemy and lands a precise strike.",
      190,
      "nearest-enemy",
      "single",
      {
        requiresTarget: false,
        signatureMechanics: [{ kind: "lunge" }],
      },
    ),
    assetPath: "/assets/characters/tashigi.png",
  },
  {
    id: "sanji",
    name: "Sanji",
    cost: 2,
    traits: ["straw-hat", "brawler"],
    stats: {
      health: 720,
      attack: 68,
      defense: 22,
      range: 1,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "diable-jambe",
      "Diable Jambe",
      "A burning kick that scorches its victim.",
      235,
      "nearest-enemy",
      "single",
      { burnPower: 18, burnDurationMs: 3_000 },
    ),
    assetPath: "/assets/characters/sanji.png",
  },
  {
    id: "robin",
    name: "Robin",
    cost: 2,
    traits: ["straw-hat", "revolutionary", "specialist"],
    stats: {
      health: 620,
      attack: 48,
      defense: 16,
      range: 4,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "clutch",
      "Clutch",
      "Immobilizes and damages the enemy with conjured limbs.",
      205,
      "lowest-health-enemy",
      "single",
      { stunMs: 1_200 },
    ),
    assetPath: "/assets/characters/robin.png",
  },
  {
    id: "smoker",
    name: "Smoker",
    cost: 2,
    traits: ["navy", "guardian"],
    stats: {
      health: 820,
      attack: 62,
      defense: 28,
      range: 2,
      attackIntervalMs: 1_200,
      moveIntervalMs: 500,
    },
    ability: ability(
      "white-blow",
      "White Blow",
      "A smoke-driven blow that sweeps a line of enemies.",
      210,
      "nearest-enemy",
      "line",
    ),
    assetPath: "/assets/characters/smoker.png",
  },
  {
    id: "sabo",
    name: "Sabo",
    cost: 2,
    traits: ["revolutionary", "brotherhood", "brawler"],
    stats: {
      health: 760,
      attack: 72,
      defense: 23,
      range: 1,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "dragon-claw",
      "Dragon Claw",
      "Crushes the target area with a powerful claw strike.",
      190,
      "nearest-enemy",
      "adjacent",
    ),
    assetPath: "/assets/characters/sabo.png",
  },
  {
    id: "luffy",
    name: "Luffy",
    cost: 3,
    traits: [
      "straw-hat",
      "supernova",
      "brotherhood",
      "captain",
      "brawler",
    ],
    stats: {
      health: 900,
      attack: 80,
      defense: 28,
      range: 2,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "gum-gum-gatling",
      "Gum-Gum Gatling",
      "Unleashes a rapid barrage across the enemy formation.",
      75,
      "nearest-enemy",
      "adjacent",
      { hits: 3 },
    ),
    assetPath: "/assets/characters/luffy.png",
  },
  {
    id: "zoro",
    name: "Zoro",
    cost: 3,
    traits: ["straw-hat", "supernova", "swordsman"],
    stats: {
      health: 880,
      attack: 92,
      defense: 30,
      range: 1,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "oni-giri",
      "Oni Giri",
      "Strikes three times. Remaining strikes redirect after a KO, and the final strike deals more damage to low-health enemies.",
      355,
      "lowest-health-enemy",
      "single",
      {
        sequentialStrike: {
          hitWeightsBasisPoints: [3_000, 3_000, 4_000],
          retargetOnKill: "nearest-in-range",
          finalHitBonus: {
            healthThresholdPercent: 35,
            damageBonusPercent: 25,
          },
        },
      },
    ),
    assetPath: "/assets/characters/zoro.png",
  },
  {
    id: "kid",
    name: "Kid",
    cost: 3,
    traits: ["supernova", "captain"],
    stats: {
      health: 920,
      attack: 78,
      defense: 32,
      range: 2,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "magnetic-crush",
      "Magnetic Crush",
      "Compacts metal around a group of enemies.",
      275,
      "nearest-enemy",
      "adjacent",
      { stunMs: 800 },
    ),
    assetPath: "/assets/characters/kid.png",
  },
  {
    id: "crocodile",
    name: "Crocodile",
    cost: 3,
    traits: ["warlord", "specialist", "marksman"],
    stats: {
      health: 760,
      attack: 74,
      defense: 22,
      range: 4,
      attackIntervalMs: 1_100,
      moveIntervalMs: 500,
    },
    ability: ability(
      "desert-spada",
      "Desert Spada",
      "Sends a cutting blade of sand through an enemy line.",
      300,
      "farthest-enemy",
      "line",
    ),
    assetPath: "/assets/characters/crocodile.png",
  },
  {
    id: "law",
    name: "Law",
    cost: 4,
    traits: ["supernova", "warlord", "captain"],
    stats: {
      health: 900,
      attack: 86,
      defense: 28,
      range: 3,
      attackIntervalMs: 1_000,
      moveIntervalMs: 400,
    },
    ability: ability(
      "room-shambles",
      "ROOM/Shambles",
      "Manipulates a wide ROOM and strikes every enemy inside.",
      195,
      "nearest-enemy",
      "all-enemies",
    ),
    assetPath: "/assets/characters/law.png",
  },
  {
    id: "ace",
    name: "Ace",
    cost: 4,
    traits: ["brotherhood", "marksman"],
    stats: {
      health: 820,
      attack: 90,
      defense: 22,
      range: 5,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "fire-fist",
      "Fire Fist",
      "Engulfs a cluster of enemies in a blazing fist.",
      390,
      "farthest-enemy",
      "adjacent",
      { burnPower: 28, burnDurationMs: 4_000 },
    ),
    assetPath: "/assets/characters/ace.png",
  },
  {
    id: "hancock",
    name: "Hancock",
    cost: 4,
    traits: ["warlord", "specialist"],
    stats: {
      health: 850,
      attack: 82,
      defense: 26,
      range: 4,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "mero-mero",
      "Mero Mero",
      "Petrifies and damages enemies across the battlefield.",
      235,
      "nearest-enemy",
      "all-enemies",
      { stunMs: 1_000 },
    ),
    assetPath: "/assets/characters/hancock.png",
  },
  {
    id: "doflamingo",
    name: "Doflamingo",
    cost: 4,
    traits: ["warlord", "specialist"],
    stats: {
      health: 900,
      attack: 88,
      defense: 28,
      range: 4,
      attackIntervalMs: 1_000,
      moveIntervalMs: 500,
    },
    ability: ability(
      "string-bind",
      "String Bind",
      "Binds a cluster in razor wire and leaves them stunned.",
      315,
      "lowest-health-enemy",
      "adjacent",
      { stunMs: 1_400 },
    ),
    assetPath: "/assets/characters/doflamingo.png",
  },
  {
    id: "garp",
    name: "Garp",
    cost: 5,
    traits: ["navy", "guardian", "brawler"],
    stats: {
      health: 1_250,
      attack: 110,
      defense: 45,
      range: 2,
      attackIntervalMs: 1_100,
      moveIntervalMs: 400,
    },
    ability: ability(
      "galaxy-impact",
      "Galaxy Impact",
      "Shatters the battlefield with a colossal shock wave.",
      360,
      "nearest-enemy",
      "all-enemies",
      { stunMs: 1_000, castAnimationMs: 700 },
    ),
    assetPath: "/assets/characters/garp.png",
  },
  {
    id: "mihawk",
    name: "Mihawk",
    cost: 5,
    traits: ["warlord", "swordsman"],
    stats: {
      health: 1_000,
      attack: 135,
      defense: 36,
      range: 3,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: ability(
      "black-blade-wave",
      "Black Blade Wave",
      "Launches an overwhelming slash through an enemy line.",
      660,
      "farthest-enemy",
      "line",
      { castAnimationMs: 700 },
    ),
    assetPath: "/assets/characters/mihawk.png",
  },
];

export const TRAIT_DEFINITIONS: TraitDefinition[] = [
  {
    id: "straw-hat",
    name: "Straw Hat",
    category: "origin",
    description: "Crew bonds grant health and faster attacks.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "max-health-percent", value: 10 }],
        label: "+10% health",
      },
      {
        required: 4,
        effects: [
          { kind: "max-health-percent", value: 15 },
          { kind: "attack-speed-percent", value: 10 },
        ],
        label: "+15% health, +10% attack speed",
      },
      {
        required: 6,
        effects: [
          { kind: "max-health-percent", value: 25 },
          { kind: "attack-speed-percent", value: 20 },
        ],
        label: "+25% health, +20% attack speed",
      },
    ],
  },
  {
    id: "navy",
    name: "Navy",
    category: "origin",
    description: "Disciplined formations gain defenses.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "defense-flat", value: 14 }],
        label: "+14 defense",
      },
      {
        required: 3,
        effects: [
          { kind: "defense-flat", value: 28 },
          { kind: "shield-flat", value: 100 },
        ],
        label: "+28 defense and 100 shield",
      },
    ],
  },
  {
    id: "warlord",
    name: "Warlord",
    category: "origin",
    description: "Veterans begin energized and drain life.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "omnivamp-percent", value: 8 },
          { kind: "starting-energy", value: 10 },
        ],
        label: "8% omnivamp, +10 energy",
      },
      {
        required: 4,
        effects: [
          { kind: "omnivamp-percent", value: 18 },
          { kind: "starting-energy", value: 25 },
        ],
        label: "18% omnivamp, +25 energy",
      },
    ],
  },
  {
    id: "supernova",
    name: "Supernova",
    category: "origin",
    description: "Ambition increases attack and snowballs after takedowns.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "attack-percent", value: 8 },
          { kind: "stacking-attack-percent", value: 3 },
        ],
        label: "+8% attack, +3% per takedown",
      },
      {
        required: 4,
        effects: [
          { kind: "attack-percent", value: 18 },
          { kind: "stacking-attack-percent", value: 7 },
        ],
        label: "+18% attack, +7% per takedown",
      },
    ],
  },
  {
    id: "brotherhood",
    name: "Brotherhood",
    category: "origin",
    description: "At low health, sworn brothers gain an emergency shield.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "emergency-shield-percent", value: 22 }],
        label: "22% emergency shield",
      },
      {
        required: 3,
        effects: [{ kind: "emergency-shield-percent", value: 38 }],
        label: "38% emergency shield",
      },
    ],
  },
  {
    id: "revolutionary",
    name: "Revolutionary",
    category: "origin",
    description: "Unpredictable footwork grants dodge.",
    tiers: [
      {
        required: 1,
        effects: [{ kind: "dodge-percent", value: 10 }],
        label: "+10% dodge",
      },
      {
        required: 2,
        effects: [{ kind: "dodge-percent", value: 20 }],
        label: "+20% dodge",
      },
    ],
  },
  {
    id: "captain",
    name: "Captain",
    category: "role",
    description: "Captains inspire their formation with opening shields.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "shield-flat", value: 100 }],
        label: "100 starting shield",
      },
      {
        required: 3,
        effects: [{ kind: "shield-flat", value: 225 }],
        label: "225 starting shield",
      },
    ],
  },
  {
    id: "brawler",
    name: "Brawler",
    category: "role",
    description: "Close-range fighters gain health and speed.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "max-health-percent", value: 6 },
          { kind: "attack-speed-percent", value: 4 },
        ],
        label: "+6% health, +4% attack speed",
      },
      {
        required: 4,
        effects: [
          { kind: "max-health-percent", value: 25 },
          { kind: "attack-speed-percent", value: 18 },
        ],
        label: "+25% health, +18% attack speed",
      },
    ],
  },
  {
    id: "swordsman",
    name: "Swordsman",
    category: "role",
    description: "Blade users gain critical strike chance.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "critical-chance-percent", value: 18 }],
        label: "+18% critical chance",
      },
      {
        required: 3,
        effects: [{ kind: "critical-chance-percent", value: 38 }],
        label: "+38% critical chance",
      },
    ],
  },
  {
    id: "marksman",
    name: "Marksman",
    category: "role",
    description: "Ranged experts gain reach and precision.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "range-flat", value: 1 },
          { kind: "critical-chance-percent", value: 10 },
        ],
        label: "+1 range, +10% critical chance",
      },
      {
        required: 3,
        effects: [
          { kind: "range-flat", value: 2 },
          { kind: "critical-chance-percent", value: 20 },
        ],
        label: "+2 range, +20% critical chance",
      },
    ],
  },
  {
    id: "specialist",
    name: "Specialist",
    category: "role",
    description: "Technical fighters amplify their abilities.",
    tiers: [
      {
        required: 2,
        effects: [{ kind: "ability-power-percent", value: 20 }],
        label: "+20% ability power",
      },
      {
        required: 4,
        effects: [
          { kind: "ability-power-percent", value: 45 },
          { kind: "starting-energy", value: 15 },
        ],
        label: "+45% ability power, +15 energy",
      },
    ],
  },
  {
    id: "guardian",
    name: "Guardian",
    category: "role",
    description: "Frontliners begin protected and resist attacks.",
    tiers: [
      {
        required: 2,
        effects: [
          { kind: "defense-flat", value: 15 },
          { kind: "shield-flat", value: 90 },
        ],
        label: "+15 defense, 90 shield",
      },
      {
        required: 3,
        effects: [
          { kind: "defense-flat", value: 32 },
          { kind: "shield-flat", value: 220 },
        ],
        label: "+32 defense, 220 shield",
      },
    ],
  },
];

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: "black-blade",
    name: "Black Blade",
    description: "A supreme blade for raw and critical damage.",
    icon: "†",
    effects: [
      { kind: "attack-flat", value: 24 },
      { kind: "critical-chance-percent", value: 12 },
    ],
  },
  {
    id: "meat-platter",
    name: "Meat Platter",
    description: "A hearty meal that greatly increases health.",
    icon: "✚",
    effects: [{ kind: "health-flat", value: 300 }],
  },
  {
    id: "clima-tact",
    name: "Clima-Tact",
    description: "Empowers abilities and supplies starting energy.",
    icon: "ϟ",
    effects: [
      { kind: "ability-power-percent", value: 25 },
      { kind: "starting-energy", value: 20 },
    ],
  },
  {
    id: "sniper-goggles",
    name: "Sniper Goggles",
    description: "Extends attack range and improves critical aim.",
    icon: "◎",
    effects: [
      { kind: "range-flat", value: 1 },
      { kind: "critical-chance-percent", value: 15 },
    ],
  },
  {
    id: "sea-prism-stone",
    name: "Sea Prism Stone",
    description: "Dense protection against physical pressure.",
    icon: "◆",
    effects: [
      { kind: "defense-flat", value: 25 },
      { kind: "health-flat", value: 120 },
    ],
  },
  {
    id: "armament-wraps",
    name: "Armament Wraps",
    description: "Reinforces both attacks and defenses.",
    icon: "◈",
    effects: [
      { kind: "attack-flat", value: 14 },
      { kind: "defense-flat", value: 14 },
    ],
  },
  {
    id: "den-den-mushi",
    name: "Den Den Mushi",
    description: "Coordinates faster attacks and an earlier ability.",
    icon: "☏",
    effects: [
      { kind: "attack-speed-percent", value: 18 },
      { kind: "starting-energy", value: 10 },
    ],
  },
  {
    id: "cola-engine",
    name: "Cola Engine",
    description: "A high-powered engine for speed and sustain.",
    icon: "⚙",
    effects: [
      { kind: "health-flat", value: 160 },
      { kind: "attack-speed-percent", value: 12 },
      { kind: "omnivamp-percent", value: 8 },
    ],
  },
];

const basicEnemyAbility = (
  id: string,
  name: string,
  power: number,
): UnitDefinition["ability"] =>
  ability(id, name, `${name} damages its target.`, power, "nearest-enemy", "single");

export const PVE_ENEMY_DEFINITIONS: PvEEnemyDefinition[] = [
  {
    id: "marine-recruit",
    name: "Marine Recruit",
    stats: {
      health: 420,
      attack: 38,
      defense: 10,
      range: 1,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    assetPath: "/assets/enemies/marine-recruit.png",
  },
  {
    id: "rifle-marine",
    name: "Rifle Marine",
    stats: {
      health: 380,
      attack: 48,
      defense: 8,
      range: 5,
      attackIntervalMs: 1_400,
      moveIntervalMs: 500,
    },
    ability: basicEnemyAbility("rifle-volley", "Rifle Volley", 110),
    assetPath: "/assets/enemies/rifle-marine.png",
  },
  {
    id: "pirate-raider",
    name: "Pirate Raider",
    stats: {
      health: 600,
      attack: 62,
      defense: 16,
      range: 1,
      attackIntervalMs: 900,
      moveIntervalMs: 400,
    },
    ability: basicEnemyAbility("reckless-slash", "Reckless Slash", 145),
    assetPath: "/assets/enemies/pirate-raider.png",
  },
  {
    id: "sea-king",
    name: "Sea King",
    stats: {
      health: 1_600,
      attack: 88,
      defense: 28,
      range: 2,
      attackIntervalMs: 1_300,
      moveIntervalMs: 500,
    },
    ability: {
      ...basicEnemyAbility("tidal-roar", "Tidal Roar", 190),
      pattern: "adjacent",
      stunMs: 600,
    },
    assetPath: "/assets/enemies/sea-king.png",
  },
  {
    id: "pacifista",
    name: "Pacifista",
    stats: {
      health: 2_100,
      attack: 105,
      defense: 38,
      range: 5,
      attackIntervalMs: 1_400,
      moveIntervalMs: 600,
    },
    ability: {
      ...basicEnemyAbility("laser-beam", "Laser Beam", 285),
      pattern: "line",
    },
    assetPath: "/assets/enemies/pacifista.png",
  },
];

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    id: "east-blue-patrol",
    round: 1,
    kind: "pve",
    name: "East Blue Patrol",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [{ enemyId: "marine-recruit", count: 2 }],
    itemChoices: 3,
  },
  {
    id: "rifle-line",
    round: 2,
    kind: "pve",
    name: "Rifle Line",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "marine-recruit", count: 2 },
      { enemyId: "rifle-marine", count: 1 },
    ],
    itemChoices: 3,
  },
  {
    id: "raider-ambush",
    round: 3,
    kind: "pve",
    name: "Raider Ambush",
    preparationSeconds: 20,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "marine-recruit", count: 2 },
      { enemyId: "pirate-raider", count: 1 },
    ],
    itemChoices: 3,
  },
  {
    id: "first-muster",
    round: 4,
    kind: "carousel",
    name: "First Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "calm-belt",
    round: 9,
    kind: "pve",
    name: "Calm Belt",
    preparationSeconds: 40,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "sea-king", count: 1 },
      { enemyId: "pirate-raider", count: 2 },
    ],
    itemChoices: 3,
  },
  {
    id: "grand-line-muster",
    round: 12,
    kind: "carousel",
    name: "Grand Line Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "pacifista-test",
    round: 14,
    kind: "pve",
    name: "Pacifista Test",
    preparationSeconds: 30,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "pacifista", count: 1 },
      { enemyId: "rifle-marine", count: 2 },
    ],
    itemChoices: 3,
  },
  {
    id: "new-world-muster",
    round: 17,
    kind: "carousel",
    name: "New World Muster",
    preparationSeconds: 30,
    battleSeconds: 45,
  },
  {
    id: "siege-of-justice",
    round: 19,
    kind: "pve",
    name: "Siege of Justice",
    preparationSeconds: 40,
    battleSeconds: 45,
    enemyWave: [
      { enemyId: "pacifista", count: 2 },
      { enemyId: "sea-king", count: 1 },
    ],
    itemChoices: 3,
  },
];

export const BOT_PERSONALITIES: BotPersonality[] = [
  {
    id: "balanced",
    name: "Balanced",
    economyReserve: 10,
    levelAggression: 0.55,
    rerollAggression: 0.45,
    preferredTraits: [],
    formation: "spread",
  },
  {
    id: "treasurer",
    name: "Treasurer",
    economyReserve: 25,
    levelAggression: 0.35,
    rerollAggression: 0.2,
    preferredTraits: ["straw-hat", "captain"],
    formation: "corner",
  },
  {
    id: "high-roller",
    name: "High Roller",
    economyReserve: 5,
    levelAggression: 0.3,
    rerollAggression: 0.9,
    preferredTraits: ["supernova", "swordsman"],
    formation: "frontline",
  },
  {
    id: "vanguard",
    name: "Vanguard",
    economyReserve: 8,
    levelAggression: 0.85,
    rerollAggression: 0.25,
    preferredTraits: ["navy", "guardian"],
    formation: "frontline",
  },
  {
    id: "strategist",
    name: "Strategist",
    economyReserve: 15,
    levelAggression: 0.6,
    rerollAggression: 0.5,
    preferredTraits: ["specialist", "warlord"],
    formation: "corner",
  },
  {
    id: "sharpshooter",
    name: "Sharpshooter",
    economyReserve: 12,
    levelAggression: 0.5,
    rerollAggression: 0.55,
    preferredTraits: ["marksman", "revolutionary"],
    formation: "corner",
  },
  {
    id: "brawler",
    name: "Brawler",
    economyReserve: 7,
    levelAggression: 0.65,
    rerollAggression: 0.65,
    preferredTraits: ["brawler", "brotherhood"],
    formation: "frontline",
  },
];

export const GAME_CONFIG: GameConfig = {
  boardWidth: 8,
  boardHeight: 6,
  deployRows: 3,
  benchSize: 8,
  shopSize: 6,
  itemCap: 3,
  playerCount: 8,
  startHealth: 100,
  startGold: 5,
  startLevel: 2,
  maxLevel: 9,
  rerollCost: 1,
  buyXpCost: 4,
  buyXpAmount: 4,
  autoXpPerRound: 2,
  baseIncome: 5,
  maxInterest: 5,
  maxStreakBonus: 5,
  pvpWinGold: 1,
  poolCopiesByCost: [27, 22, 18, 14, 10],
  shopOddsByLevel: {
    "2": [1, 0, 0, 0, 0],
    "3": [0.7, 0.3, 0, 0, 0],
    "4": [0.5, 0.4, 0.1, 0, 0],
    "5": [0.36, 0.42, 0.2, 0.02, 0],
    "6": [0.25, 0.4, 0.3, 0.05, 0],
    "7": [0.16, 0.33, 0.35, 0.15, 0.01],
    "8": [0.11, 0.27, 0.35, 0.22, 0.05],
    "9": [0.05, 0.2, 0.35, 0.3, 0.1],
  },
  xpToNextByLevel: {
    "2": 2,
    "3": 6,
    "4": 10,
    "5": 22,
    "6": 34,
    "7": 52,
    "8": 72,
  },
  starStatBasisPoints: [10_000, 18_000, 32_400],
  starAbilityBasisPoints: [10_000, 15_000, 22_500],
  combatTickMs: 100,
  combatMaxTicks: 450,
  recordBattleEvents: true,
};

export const DEFAULT_CONTENT: GameContent = {
  version: "1.3.0",
  units: UNIT_DEFINITIONS,
  traits: TRAIT_DEFINITIONS,
  items: ITEM_DEFINITIONS,
  enemies: PVE_ENEMY_DEFINITIONS,
  stages: STAGE_DEFINITIONS,
  botPersonalities: BOT_PERSONALITIES,
  config: GAME_CONFIG,
};

export const CONTENT = DEFAULT_CONTENT;

export function getUnitDefinition(
  id: string,
  content: Pick<GameContent, "units"> = DEFAULT_CONTENT,
): UnitDefinition | null {
  return content.units.find((unit) => unit.id === id) ?? null;
}

export function getTraitDefinition(
  id: string,
  content: Pick<GameContent, "traits"> = DEFAULT_CONTENT,
): TraitDefinition | null {
  return content.traits.find((trait) => trait.id === id) ?? null;
}

export function getItemDefinition(
  id: string,
  content: Pick<GameContent, "items"> = DEFAULT_CONTENT,
): ItemDefinition | null {
  return content.items.find((item) => item.id === id) ?? null;
}

export function getStageDefinition(
  round: number,
  content: GameContent = DEFAULT_CONTENT,
): StageDefinition {
  const preparationSecondsByRound: Record<string, number> = {
    "1": 20,
    "2": 20,
    "3": 20,
    "5": 40,
    "8": 40,
    "9": 40,
    "10": 50,
    "11": 40,
    "15": 40,
    "19": 40,
    "20": 50,
  };
  return (
    content.stages.find((stage) => stage.round === round) ?? {
      id: `pvp-${round}`,
      round,
      kind: "pvp",
      name: `Rival Battle ${round}`,
      preparationSeconds: preparationSecondsByRound[String(round)] ?? 30,
      battleSeconds: 45,
    }
  );
}
